### ISSUE TITLE
TX Server Issues?

### ISSUE THREAD

**Issue by sathamneh** [inferno-framework/fhir-validator-wrapper#70]
Hi everyone, 

It seems there is an issue with the TX Server, I am trying to select an Implementation guide, and the menu keep loading without showing anything. 

Best Regards.
Suheel.

**Comment by dehall** [comment]
Hi, as mentioned in the linked issue, the root problem with the package server was corrected overnight and I now see the IG list loading in the validator app again, so I'm going to close this issue. (You may need to refresh the page if it's been open.) Please feel free to re-open if you're still seeing a problem
